// <auto-generated />
namespace Investips.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddBearRelatedPropertiesSignals : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddBearRelatedPropertiesSignals));
        
        string IMigrationMetadata.Id
        {
            get { return "201906231022024_AddBearRelatedPropertiesSignals"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
